name: Daily Release

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  install-format-test-build-commit-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Load pip cache
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-poetry-poe-semver
          restore-keys: |
            ${{ runner.os }}-pip-poetry-poe-semver
      - name: Install system dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry poethepoet poetry-dynamic-versioning

      - name: Load poetry cache
        id: poetry-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
            ${{ runner.os }}-poetry-
      - name: Update the dependencies using poetry
        run: |
          poetry update
          poetry config --list

      - name: Format with isort
        run: poe format-imports
      - name: Format with black
        run: poe format

      - name: Test with pytest
        run: poe test
      - name: Lint with flake8
        run: |
          # Show the plugins used for linting
          poe lint-plugins
          # exit-zero treats all errors as warnings.
          poe lint --count --exit-zero --statistics

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.PGP_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-tag-gpgsign: true

      - name: Setup git config
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Sam"
          git config --global user.email dev@samarthj.com
          git config --global user.signkey dev@samarthj.com
          git config --global commit.gpgsign true
          git config --global tag.gpgsign true
          git config --global init.defaultBranch main
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Delete Prerelease
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          prerelease="$(gh release list | grep -i pre-release | cut -f1)"
          echo $prerelease
          if [[ -n "${prerelease}" ]]; then
            echo "current pre-release - $prerelease"
            gh release delete -y "${prerelease}" || true
          fi

      - name: Version Evaluation
        id: version
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          poetry-dynamic-versioning
          echo "$(poetry version -s)"
          version_base="$(poetry version -s | sed -re 's|^([0-9.]+)([abrc]*)([0-9]*)|\1|g')"
          version_stage="$(poetry version -s | sed -re 's|^([0-9.]+)([abrc]*)([0-9]*)|\2|g')"
          version_revision="$(poetry version -s | sed -re 's|^([0-9.]+)([abrc]*)([0-9]*)|\3|g')"
          echo "::set-output name=version_base::$version_base"
          echo "::set-output name=version_stage::$version_stage"
          echo "::set-output name=version_revision::$version_revision"
          echo "::set-output name=version_full::$(poetry version -s)"
          echo "$version_base $version_stage $version_revision $version_full"
          poetry version minor
          next_base="$(poetry version -s | sed -re 's|^([0-9.]+)([abrc]*)([0-9]*)|\1|g')"
          major="$(echo $next_base | sed -re 's|^([0-9]+).([0-9]+).([0-9]+)|\1|g')"
          minor="$(echo $next_base | sed -re 's|^([0-9]+).([0-9]+).([0-9]+)|\2|g')"
          next_tag="${major}.${minor}"
          next_release="${major}.${minor}.${version_revision}"
          next_prerelease="${next_base}${version_stage}${version_revision}"
          echo "Delete next tag if exists - v$next_tag"
          git tag --delete "v${next_tag}" || true
          git push --delete origin "v${next_tag}" || true
          echo "$next_base $next_release $next_prerelease"
          echo "::set-output name=next_tag::$next_tag"
          echo "::set-output name=next_base::$next_base"
          echo "::set-output name=next_release::$next_release"
          echo "::set-output name=next_prerelease::${next_prerelease}"

      - name: Release Evaluation ${{ steps.version.outputs.next_release }}
        id: release
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          [[ "${{ steps.version.outputs.version_stage }}" == "rc" ]] && [[ ${{ steps.version.outputs.version_revision }} -gt 3 ]]

      - name: Set Release Version ${{ steps.version.outputs.version_full }} -> ${{ steps.version.outputs.next_release }}
        id: set_release
        if: ${{ steps.release.outcome == 'success' }}
        run: |
          poetry version ${{ steps.version.outputs.next_release }}
      - name: Set Prerelease Version ${{ steps.version.outputs.version_full }} -> ${{ steps.version.outputs.next_prerelease }}
        id: set_prerelease
        if: ${{ steps.release.outcome == 'failure' }}
        shell: bash
        run: |
          poetry version ${{ steps.version.outputs.next_prerelease }}

      - name: Commit and Build ${{ steps.version.outputs.next_release }}
        id: commit_build
        if: ${{ (steps.set_release.outcome == 'success') || (steps.set_prerelease.outcome == 'success') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git status
          git commit -S -m "ci(github-actions): :construction_worker: v$(poetry version -s)"
          poetry run cz changelog --unreleased-version "v$(poetry version -s)"
          git tag "v${{ steps.version.outputs.next_tag }}" -m "v${{ steps.version.outputs.next_tag }}"
          git push --follow-tags
          poetry build

      - name: Release ${{ steps.version.outputs.next_release }}
        if: ${{ (steps.set_release.outcome == 'success') && (steps.commit_build.outcome == 'success') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prev_release="$(gh release list -L 2 | tail -n1 | grep -i pre-release | cut -f1)"
          [[ "v${{ steps.version.outputs.next_release }}" == "${prev_release}" ]] && exit 0
          poetry run cz changelog --unreleased-version "v${{ steps.version.outputs.next_release }}" --start-rev "${prev_release}"
          gh release create --target "v${{ steps.version.outputs.next_tag }}" -F CHANGELOG.md -t "v${{ steps.version.outputs.next_release }}" ./dist/*.tar.gz ./dist/*.whl

      - name: Prerelease ${{ steps.version.outputs.next_prerelease }}
        if: ${{ (steps.set_prerelease.outcome == 'success') && (steps.commit_build.outcome == 'success') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prev_release="$(gh release list -L 2 | tail -n1 | grep -i pre-release | cut -f1)"
          [[ "v${{ steps.version.outputs.next_prerelease }}" == "${prev_release}" ]] && exit 0
          poetry run cz changelog --unreleased-version "v${{ steps.version.outputs.next_prerelease }}" --start-rev "${prev_release}"
          gh release create --target "v${{ steps.version.outputs.next_tag }}" --prerelease -F CHANGELOG.md -t "v${{ steps.version.outputs.next_prerelease }}" ./dist/*.tar.gz ./dist/*.whl

